### ISSUE TITLE
0.0.3: build error

### ISSUE THREAD

**Issue by ponsfoot** [Martchus/reflective-rapidjson#2]
Build & Platform:
Build 2018-04-02 on ArchLinux

Versions:
c++utilities 4.13.0
clang 6.0.0
llvm-libs 6.0.0
rapidjson 1.1.0
cppunit 1.14.0
boost 1.66.0
cmake 3.10.3
llvm 6.0.0

Overview:
0.0.3 build fails as follows:

$ makepkg -s
==> Making package: reflective-rapidjson 0.0.3-1 (Mon Apr  2 17:03:47 JST 2018)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found reflective-rapidjson-0.0.3.tar.gz
==> Validating source files with sha256sums...
    reflective-rapidjson-0.0.3.tar.gz ... Passed
==> Extracting sources...
  -> Extracting reflective-rapidjson-0.0.3.tar.gz with bsdtar
==> Starting prepare()...
==> Starting build()...
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using system c++utilities
-- RapidJSON found. Headers: /usr/include
-- Configuring project reflective_rapidjson
fatal: Not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-- Using default CXX11 ABI (not forcing old CX11 ABI).
-- For the check target to work, it is required to call enable_testing() on the source directory root.
-- Project reflective_rapidjson is header-only library.
-- Using template for global.h from CPP_UTILITIES installation.
-- reflective_rapidjson: BUILD_SHARED_LIBS=ON
-- Using template for Config.cmake from CPP_UTILITIES installation.
-- Using template for SharedConfig.cmake from CPP_UTILITIES installation.
-- Using template for template.pc from CPP_UTILITIES installation.
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for one of the modules 'cppunit>=1.13.0'
-- Linking test target dynamically against reflective_rapidjson
-- Using template for doxygen from CPP_UTILITIES installation.
CMake Warning at /usr/share/c++utilities/cmake/modules/Doxygen.cmake:31 (message):
  Doxygen not found, unable to add target for generating API documentation
  for reflective_rapidjson
Call Stack (most recent call first):
  lib/CMakeLists.txt:55 (include)

-- Using template for config.h from CPP_UTILITIES installation.
-- Linking reflective_rapidjson_generator dynamically against external library CPP_UTILITIES (c++utilities).
-- Adding dynamic external library CPP_UTILITIES (c++utilities) to dependencies of static reflective_rapidjson_generator.
-- Configuring project reflective_rapidjson_generator
fatal: Not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-- Using default CXX11 ABI (not forcing old CX11 ABI).
-- For the check target to work, it is required to call enable_testing() on the source directory root.
-- Using template for desktop from CPP_UTILITIES installation.
-- Using template for appdata.xml from CPP_UTILITIES installation.
-- Checking for one of the modules 'cppunit>=1.13.0'
-- Using template for bash-completion.sh from CPP_UTILITIES installation.
-- Generating files for bash completion.
-- Using template for doxygen from CPP_UTILITIES installation.
CMake Warning at /usr/share/c++utilities/cmake/modules/Doxygen.cmake:31 (message):
  Doxygen not found, unable to add target for generating API documentation
  for reflective_rapidjson_generator
Call Stack (most recent call first):
  generator/CMakeLists.txt:62 (include)

-- Using /usr/lib/clang/6.0.0 as Clang's resource directory for Reflective RapidJSON
-- Adding generator command for tests/structs.h producing /home/hashimo/Downloads/reflective-rapidjson/src/reflective-rapidjson-0.0.3/generator/reflection/structs.h
-- Adding generator command for tests/morestructs.h producing /home/hashimo/Downloads/reflective-rapidjson/src/reflective-rapidjson-0.0.3/generator/reflection/morestructs.h
-- Adding generator command for tests/cppunit.cpp producing /home/hashimo/Downloads/reflective-rapidjson/src/reflective-rapidjson-0.0.3/generator/reflection/cppunit.h
-- Using template for config.h from CPP_UTILITIES installation.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hashimo/Downloads/reflective-rapidjson/src/reflective-rapidjson-0.0.3
Scanning dependencies of target reflective_rapidjson_generator_testlib
Scanning dependencies of target reflective_rapidjson_generator
[  5%] Building CXX object generator/CMakeFiles/reflective_rapidjson_generator_testlib.dir/codegenerator.cpp.o
[ 11%] Building CXX object generator/CMakeFiles/reflective_rapidjson_generator_testlib.dir/codefactory.cpp.o
[ 17%] Building CXX object generator/CMakeFiles/reflective_rapidjson_generator_testlib.dir/jsonserializationcodegenerator.cpp.o
[ 23%] Building CXX object generator/CMakeFiles/reflective_rapidjson_generator_testlib.dir/frontendaction.cpp.o
[ 29%] Building CXX object generator/CMakeFiles/reflective_rapidjson_generator.dir/codegenerator.cpp.o
[ 35%] Building CXX object generator/CMakeFiles/reflective_rapidjson_generator_testlib.dir/consumer.cpp.o
[ 41%] Building CXX object generator/CMakeFiles/reflective_rapidjson_generator.dir/jsonserializationcodegenerator.cpp.o
[ 47%] Building CXX object generator/CMakeFiles/reflective_rapidjson_generator_testlib.dir/clangversionabstraction.cpp.o
[ 52%] Building CXX object generator/CMakeFiles/reflective_rapidjson_generator_testlib.dir/visitor.cpp.o
[ 58%] Building CXX object generator/CMakeFiles/reflective_rapidjson_generator.dir/codefactory.cpp.o
[ 64%] Building CXX object generator/CMakeFiles/reflective_rapidjson_generator.dir/frontendaction.cpp.o
[ 70%] Building CXX object generator/CMakeFiles/reflective_rapidjson_generator.dir/consumer.cpp.o
[ 76%] Building CXX object generator/CMakeFiles/reflective_rapidjson_generator.dir/clangversionabstraction.cpp.o
[ 82%] Building CXX object generator/CMakeFiles/reflective_rapidjson_generator.dir/visitor.cpp.o
[ 88%] Building CXX object generator/CMakeFiles/reflective_rapidjson_generator.dir/main.cpp.o
[ 94%] Linking CXX shared library libreflective_rapidjson_generator_testlib.so
[ 94%] Built target reflective_rapidjson_generator_testlib
[100%] Linking CXX executable reflective_rapidjson_generator
/usr/bin/ld: CMakeFiles/reflective_rapidjson_generator.dir/consumer.cpp.o: undefined reference to symbol '_ZNK5clang10LambdaExpr7getBodyEv'
/usr/lib/../lib/libclangAST.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [generator/CMakeFiles/reflective_rapidjson_generator.dir/build.make:279: generator/reflective_rapidjson_generator] Error 1
make[1]: *** [CMakeFiles/Makefile2:782: generator/CMakeFiles/reflective_rapidjson_generator.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by Martchus** [comment]
This is fixed in v0.0.4. Seems I have forgotten to update the AUR package. I will update it later. Till then, see my PKGBUILDs repo.

**Comment by ponsfoot** [comment]
Confirmed.
Thx
